# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: myComputer

variables:
 yamlTarget: $(target)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
     Write-Host "Build Source Branch Name: "${env:BUILD_SOURCEBRANCH}
     Write-Host "Pipeline Workspace: "${env:PIPELINE_WORKSPACE}
     Write-Host "##vso[task.setvariable variable=SPTARGET;]$(yamlTarget)"
     Write-Host "##vso[task.setvariable variable=JavaVersion;]17"
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '$(JavaVersion)'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: '$(pipeline.workspace)/Java/jdk-17.0.10_windows-x64_bin.zip'
    jdkDestinationDirectory: '$(pipeline.workspace)/javainstall'
    cleanDestinationDirectory: true
- task: Ant@1
  inputs:
    options: -DSPTARGET=$(SPTARGET)
    buildFile: 'build.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(JavaVersion)
    jdkArchitectureOption: x64
    targets: war